### PR TITLE
Update flang

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by xoviat** [comment]
Is there a particular reason to use the llvm version? IMO the version could be `0.2018.1.1`.

**Comment by isuruf** [comment]
We already have builds with `5.0.0` so `0.2018.1.1` will be lower than that. I don't want to remove the 5.0.0 builds because other people might be depending on it

**Comment by xoviat** [comment]
But we have builds with `2017.12.15` and such. Who else has flang pinned as a dependency?

**Comment by isuruf** [comment]
I think the vcpkg PR uses 5.0.0 builds

**Comment by xoviat** [comment]
Good point. We could put `5.2018.1.1` builds.

**Comment by xoviat** [comment]
The reason that I'm hesitant about the build number is that people would be unable to pin dependencies, which could be problematic when we make a mistake.

**Comment by isuruf** [comment]
Pinning can be done with the build umber.

**Comment by xoviat** [comment]
Okay, then. +1 for merge then.

**Pull request merged**
