### PR TITLE
WIP: LLVM flang 16.0.x

### PR DESCRIPTION
**Pull request by h-vetinari**
Trying #25 + update to 16.0

### CODE REVIEW

**Comment by h-vetinari** [comment]
@isuruf, aside from windows not working yet, I'd be glad to have your input on how a future `libflang` output should look in an LLVM world. Instead of `libflang.so`, we now have:
```
[...]
-- Installing: $PREFIX/include/flang/Version.inc
-- Installing: $PREFIX/lib/libFortranCommon.so.16
-- Installing: $PREFIX/lib/libFortranCommon.so
-- Installing: $PREFIX/lib/libFortranEvaluate.so.16
-- Installing: $PREFIX/lib/libFortranEvaluate.so
-- Installing: $PREFIX/lib/libFortranDecimal.so.16
-- Installing: $PREFIX/lib/libFortranDecimal.so
-- Installing: $PREFIX/lib/libFortranLower.so.16
-- Installing: $PREFIX/lib/libFortranLower.so
-- Installing: $PREFIX/lib/libFortranParser.so.16
-- Installing: $PREFIX/lib/libFortranParser.so
-- Installing: $PREFIX/lib/libFortranSemantics.so.16
-- Installing: $PREFIX/lib/libFortranSemantics.so
-- Installing: $PREFIX/lib/libflangFrontend.so.16
-- Installing: $PREFIX/lib/libflangFrontend.so
-- Installing: $PREFIX/lib/libflangFrontendTool.so.16
-- Installing: $PREFIX/lib/libflangFrontendTool.so
-- Installing: $PREFIX/lib/libFIRBuilder.so.16
-- Installing: $PREFIX/lib/libFIRBuilder.so
-- Installing: $PREFIX/lib/libFIRCodeGen.so.16
-- Installing: $PREFIX/lib/libFIRCodeGen.so
-- Installing: $PREFIX/lib/libFIRDialect.so.16
-- Installing: $PREFIX/lib/libFIRDialect.so
-- Installing: $PREFIX/lib/libHLFIRDialect.so.16
-- Installing: $PREFIX/lib/libHLFIRDialect.so
-- Installing: $PREFIX/lib/libHLFIRTransforms.so.16
-- Installing: $PREFIX/lib/libHLFIRTransforms.so
-- Installing: $PREFIX/lib/libFIRSupport.so.16
-- Installing: $PREFIX/lib/libFIRSupport.so
-- Installing: $PREFIX/lib/libFIRTransforms.so.16
-- Installing: $PREFIX/lib/libFIRTransforms.so
-- Installing: $PREFIX/lib/libFIRAnalysis.so.16
-- Installing: $PREFIX/lib/libFIRAnalysis.so
-- Installing: $PREFIX/lib/cmake/flang/FlangTargets.cmake
[...]
```

I'm guessing `libflang` would then be the totality of those shared libs? Or do we want to drop that output?

**Comment by isuruf** [comment]
None of those. Those are for the compiler and not runtime libraries for compiled projects.

**Comment by h-vetinari** [comment]
> None of those. Those are for the compiler and not runtime libraries for compiled projects.

Thanks. I didn't know what was in the old libflang. I guess that role's then being filled by compiler-rt, and we don't need the libflang output anymore?

**Comment by isuruf** [comment]
No, it's replaced by `libFortranRuntime.so`

**Comment by h-vetinari** [comment]
> No, it's replaced by `libFortranRuntime`

OK, sounds good. It might also be necessary to add `libFortran_main.a` to that? (being installed together as below looks like an indicator that they're from the same target)

```
[...]
-- Installing: $PREFIX/bin/fir-opt
-- Installing: $PREFIX/lib/libFortranRuntime.16.dylib
-- Installing: $PREFIX/lib/libFortranRuntime.dylib
-- Installing: $PREFIX/lib/libFortran_main.a

Resource usage statistics from building flang-split:
```

**Comment by isuruf** [comment]
> It might also be necessary to add libFortran_main.a to that

No. It shouldn't be needed at runtime. Maybe as a `libfortran-main_{{ target_platform }}` output to allow cross compilation.

**Comment by h-vetinari** [comment]
> No. It shouldn't be needed at runtime. Maybe as a `libfortran-main_{{ target_platform }}` output to allow cross compilation.

I gave this a shot now, not sure if I got it as you intended on first try, happy to iterate.

**Comment by h-vetinari** [comment]
> No, it's replaced by `libFortranRuntime.so`

So that split probably doesn't work that cleanly, because `libFortranRuntime.so` depends on `libFortranDecimal.so`: 
```
WARNING (libflang,lib/libFortranRuntime.so): $RPATH/libFortranDecimal.so.16 not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```

These three seem to be the main special libs though, compare [here](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc3/flang/tools/flang-driver/CMakeLists.txt#L14-L24) from the deps of the driver.
> ```
>  # These libraries are used in the linker invocation generated by the driver
>  # (i.e. when constructing the linker job). Without them the driver would be
>  # unable to generate executables.
> ```

So it seems we need to put `libFortranDecimal` in either `libflang` or `libfortran-main`? For now I'll put it with `libflang`.

**Comment by h-vetinari** [comment]
Unsurprisingly, using an older mlir (due to the coupling between mlir/llvm/clang) when cross-compiling on osx-arm doesn't work. This would need https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/95 and something like:
```diff
--- a/recipe/conda_build_config.yaml
+++ b/recipe/conda_build_config.yaml
@@ -1,7 +1,11 @@
-c_compiler_version:            # [linux]
+# osx-arm needs newest compilers because we need mlir as a build
+# dependency (for cross-compilation), which pins llvmdev/clang
+c_compiler_version:            # [linux or (osx and arm64)]
   - 12                         # [linux]
-cxx_compiler_version:          # [linux]
+  - '*'                        # [osx and arm64]
+cxx_compiler_version:          # [linux or (osx and arm64)]
   - 12                         # [linux]
+  - '*'                        # [osx and arm64]
```

**Comment by h-vetinari** [comment]
Main problem on windows for now is that we're not [finding](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc4/cmake/Modules/HandleCompilerRT.cmake#L8) compiler-rt:
```
-- Failed to find compiler-rt builtins library for 
```

That means somehow [this](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc4/flang/CMakeLists.txt#L51) ends up calling [that function](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc4/cmake/Modules/HandleCompilerRT.cmake#L53) in a way that `$target` is unset...? 🤔

I hate the CMake DSL... 😑

**Comment by h-vetinari** [comment]
@isuruf, have you ever dealt with picking up _our_ compiler-rt on windows?

The upstream function `find_compiler_rt_library` is fully based around [using](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc4/cmake/Modules/HandleCompilerRT.cmake#L68) clang, so this fails. I've already patched out some things (exploration mainly), but it's a bit like an onion - many layers and lots of tears.

On the unix side, things build fine and we get until 
```
+ flang-new -flang-experimental-exec hello_world.f90
```
(not yet named `flang` pending https://reviews.llvm.org/D143592 / https://discourse.llvm.org/t/reviving-rename-flang-new-to-flang/68130/48)

but segfaults on osx and fails on linux with:
```
+ flang-new -flang-experimental-exec hello_world.f90
[...]/x86_64-conda-linux-gnu/bin/ld: cannot find Scrt1.o: No such file or directory
[...]x86_64-conda-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```
These files seem to be [required](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.0-rc3/clang/lib/Driver/ToolChains/Gnu.cpp#L497-L514) the clang driver, which I guess we've managed to work elsewhere somehow. AFAICT these should be coming from glibc (see [related](https://stackoverflow.com/questions/6329887/how-to-fix-linker-error-cannot-find-crt1-o) SO)? I've never encountered these though.

**Comment by h-vetinari** [comment]
> fails on linux with:
> 
> ```
> + flang-new -flang-experimental-exec hello_world.f90
> [...]/x86_64-conda-linux-gnu/bin/ld: cannot find Scrt1.o: No such file or directory
> [...]/x86_64-conda-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
> flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

These files are in the [sysroot](https://github.com/regro/libcfgraph/blob/master/artifacts/sysroot_linux-64/conda-forge/noarch/sysroot_linux-64-2.17-h4a8ded7_13.json#L691-L695). Perhaps not too surprising that a compiler would need something from there? I see that gfortran [run-depends](https://github.com/conda-forge/ctng-compilers-feedstock/blob/main/recipe/meta.yaml#L318) on the sysroot as well.

**Comment by h-vetinari** [comment]
Very strange error on windows:
```
Packaging libflang-16.0.5-h57928b3_0

(base) D:\bld\flang-split_1686639225932\work>call "C:\Miniforge\Scripts\..\condabin\conda_hook.bat" 

(base) D:\bld\flang-split_1686639225932\work>call "C:\Miniforge\Scripts\..\condabin\conda.bat" activate "D:\bld\flang-split_1686639225932\_h_env" 

EnvironmentLocationNotFound: Not a conda environment: D:\bld\flang-split_1686639225932\_build_env


(D:\bld\flang-split_1686639225932\_h_env) (base) D:\bld\flang-split_1686639225932\work>cp D:\bld\flang-split_1686639225932\work/build/bin/FortranRuntime.dll D:\bld\flang-split_1686639225932\_h_env\Library\bin\ 
cp: cannot stat 'D:\bld\flang-split_1686639225932\work/build/bin/FortranRuntime.dll': No such file or directory

(D:\bld\flang-split_1686639225932\_h_env) (base) D:\bld\flang-split_1686639225932\work>cp D:\bld\flang-split_1686639225932\work/build/bin/FortranDecimal.dll D:\bld\flang-split_1686639225932\_h_env\Library\bin\ 
cp: cannot stat 'D:\bld\flang-split_1686639225932\work/build/bin/FortranDecimal.dll': No such file or directory
```
Let's see if this persists across a restart...

**Comment by h-vetinari** [comment]
@isuruf, I'm getting closer here (though the turn-arounds are glacial...): no more segfaults on osx and windows builds 🥳 

Both problems were "solved" by switching to static builds. I can eventually raise issues for that upstream, but for now passing-on-static is way better than being blocked on shared libs (especially for a compiler package), because we're on a pretty tight schedule here for building scipy on windows for CPython 3.12 in a post-distutils world (without a [suitable](https://github.com/conda-forge/scipy-feedstock/issues/213) Fortran compiler, we won't be able to build scipy for 3.12 on windows otherwise), and I'd like to push on this a bit further (meson, scipy, etc., raising flang bugs upstream) before then.

Where I'd really need your help is in deciding the overall direction:
* do we want to call this `flang` or `llvm-flang`? Upstream [decided](https://discourse.llvm.org/t/proposal-rename-flang-new-to-flang/69462/33?u=h-vetinari) they'll aim for separate names in distributions for a while yet until it's ready to fully supplant classic flang. I don't think we're really affected by this and could just go with `flang`.
  * By extension this will probably determine whether we need/want a new feedstock or change this one
* Compiler activation: Do we want/need a separate feedstock for that? I couldn't get the sysroot to be found without the setup that `{{ compiler('cxx') }}` is doing (but failed to emulate it here myself), so as a hack I'm currently including that in the test environment
* How to deal with `libfortran-main` - you [mentioned](https://github.com/conda-forge/flang-feedstock/pull/27#issuecomment-1442545117) this as a "maybe" to allow cross-compilation. I've tried to add it here but don't really understand what needs to be done here.

Of course the commit history needs a clean-up and there's some rough corners still here and there - I'm not asking for a detailed review, but mostly for direction.

**Comment by h-vetinari** [comment]
OK, that last commit is mis-diagnosed, it's not actually a merge of build & host, but for some reason, `flang`'s very vanilla host-deps
```
      host:
        - clangdev =={{ version }}
        - compiler-rt =={{ version }}
        - llvm-openmp =={{ version }}
        - llvmdev =={{ version }}
        - mlir =={{ version }}
        # for required run-exports
        - llvm =={{ version }}
        - libclang-cpp =={{ version }}
        - {{ pin_subpackage('libflang', exact=True) }}
        - {{ pin_subpackage('libfortran-main', exact=True) }}
```

cause gcc to be installed, which pulls in libgomp. I cannot determine where a run-time dependence on gcc would be coming from?! It also looks inconsistent to me that `_openmp_mutex` allows the presence of both `libgomp` and `llvm-openmp` in the same environment. 

```
The following NEW packages will be INSTALLED [filtered]:

    _openmp_mutex:           4.5-2_gnu                 conda-forge
    gcc_impl_linux-64:       13.1.0-hc4be1a9_0         conda-forge
    libflang:                16.0.5-h59595ed_0         local      
    libfortran-main:         16.0.5-ha770c72_0         local      
    libgomp:                 13.1.0-he5830b7_0         conda-forge
    llvm-openmp:             16.0.5-h4dfa4b3_0         conda-forge
```

**Comment by h-vetinari** [comment]
As an update: the last hurdle here is how to link the compiler-rt libs on windows by default. I've asked in the issue upstream, and it seems (AFAICT) that there's something about `/MT` vs. `/MD` slipping in somewhere.

```
> flang-new -flang-experimental-exec hello_world.f90
FortranDecimal.lib(binary-to-decimal.cpp.obj) : error LNK2019: unresolved external symbol __udivti3 [snip]
> flang-new -flang-experimental-exec hello_world.f90 -l path\to\clang_rt.builtins-x86_64.lib
LINK : warning LNK4098: defaultlib 'libcmt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
> flang-new -flang-experimental-exec hello_world.f90 -l path\to\clang_rt.builtins-x86_64.lib -Wl,/NODEFAULTLIB:library
LINK : warning LNK4098: defaultlib 'libcmt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
```

More [details](https://github.com/llvm/llvm-project/issues/60730#issuecomment-1598224683)

**Comment by h-vetinari** [comment]
Some notes from a 1:1 sync with Isuru (please let me know if I got something wrong):
* Currently `{{ compiler('cxx') }}` in the test environment is necessary to properly find the sysroot on linux because of [this](https://github.com/conda-forge/clangdev-feedstock/issues/227); however the GCC-activation will set `CONDA_BUILD_SYSROOT`, which is then picked up through our [patched](https://github.com/conda-forge/clangdev-feedstock/blob/main/recipe/patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch) clang.
* `libgfortran_main` needs to depend on `libgfortran_main_{{ cross_platform }}` (not the other way around), and we need to put it on a path that's distinct per target triple to support e.g. having both x64 & aarch64 in the same environment (this will likely need patching of flang)
* for windows, we'll probably need to do something like the clang-win activation [does](https://github.com/conda-forge/clang-win-activation-feedstock/blob/main/recipe/activate-clang_win-64.bat#L12) to set +/- the equivalent of `/MD`, which will also likely have to go into a separate feedstock
* we're going to drop osx builds for now, as one compiler per language & platform is enough (and in contrast to clang, which can target the gcc runtime, flang cannot target gfortran). We're still keeping linux because it's easier to debug for general problems, but will have to make it conflict with `libgfortran-ng`.

Independently, I came across some indications in discussions upstream that the missing `__udivti3` symbol on windows is very likely related to default 128-bit support; I hope it may be possible to switch that off completely, which would probably save us from having to deal with compiler-rt at runtime.

**Comment by h-vetinari** [comment]
It looks like the runtime libs will get shuffled around quite a bit, see https://reviews.llvm.org/D154869. I'm not sure if this will land before the branch at the end of the month; I've asked in the discourse thread.

**Comment by h-vetinari** [comment]
Superseded by #28

**Pull request closed without merging**
