### PR TITLE
Split flang and libflang

### PR DESCRIPTION
**Pull request by isuruf**
This creates 2 packages `libflang` and `flang` and where the latter depends on the former. This is done because projects compiled with flang can depend only on `libflang` at runtime.

### CODE REVIEW

**Comment by isuruf** [comment]
Ignore the linter issues. It'll be fixed in https://github.com/conda-forge/conda-smithy/pull/518/files

**Comment by xoviat** [comment]
Okay.

**Comment by jakirkham** [comment]
Does this work correctly with `conda-build` 2? My impression was that version of `conda-build` does not have the ability to make split packages depend on each other. Though `conda-build` 3 should not have this problem.

**Comment by isuruf** [comment]
Yes, it works. Only difference is that in `conda-build=2` we can't use the nice `pin_subpackage` functions.

**Pull request merged**
