### PR TITLE
Build for osx

### PR DESCRIPTION
**Pull request by h-vetinari**
Mainly to be able to try a consistent LLVM stack somewhere else than on windows (and linux is out of the question because we have no `clang_linux-64`).

### CODE REVIEW

**Comment by h-vetinari** [comment]
@isuruf, I'd like to add the osx builds for flang after all (note, these would still be behind `llvm_rc` at the moment), because aside from struggling to get [flang-on-win](https://github.com/conda-forge/scipy-feedstock/pull/246#issuecomment-1722151547) past meson and working correctly, I'd like to test if flang itself can already deal with the fortran code in scipy, and linux is not a candidate unfortunately.

This PR would still need some clean-up commit-history-wise, but just wanted to check if you'd have something against publishing osx-builds for now?

**Comment by h-vetinari** [comment]
Alright, still segfaults with shared builds on osx:
```
+ flang-new hello_world.f90
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/flang-new -fc1 -triple x86_64-apple-macosx11.0.0 -emit-obj -mrelocation-model pic -pic-level 2 -target-cpu penryn -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/hello_world-4ca966.o -x f95-cpp-input hello_world.f90
 #0 0x0000000115501138 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libLLVM-17rc.dylib+0x166138)
 #1 0x00000001154ff0c8 llvm::sys::RunSignalHandlers() (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libLLVM-17rc.dylib+0x1640c8)
 #2 0x0000000115501863 SignalHandler(int) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libLLVM-17rc.dylib+0x166863)
 #3 0x00007fff2050fd7d (/usr/lib/system/libsystem_platform.dylib+0x7fff20353d7d)
 #4 0x00000001152a61f2 
 #5 0x000000012102fd33 mlir::StringAttr::get(mlir::MLIRContext*, llvm::Twine const&) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libHLFIRDialect.17rc.dylib+0xbad33)
 #6 0x00000001210fa32f mlir::OperationName::Impl::Impl(llvm::StringRef, mlir::Dialect*, mlir::TypeID, mlir::detail::InterfaceMap) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libHLFIRDialect.17rc.dylib+0x18532f)
 #7 0x000000010fe11530 mlir::RegisteredOperationName::Model<mlir::arith::AddFOp>::Model(mlir::Dialect*) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libFortranLower.17rc.dylib+0x546530)
 #8 0x000000010fe105f4 void mlir::Dialect::addOperations<mlir::arith::AddFOp, mlir::arith::AddIOp, mlir::arith::AddUIExtendedOp, mlir::arith::AndIOp, mlir::arith::BitcastOp, mlir::arith::CeilDivSIOp, mlir::arith::CeilDivUIOp, mlir::arith::CmpFOp, mlir::arith::CmpIOp, mlir::arith::ConstantOp, mlir::arith::DivFOp, mlir::arith::DivSIOp, mlir::arith::DivUIOp, mlir::arith::ExtFOp, mlir::arith::ExtSIOp, mlir::arith::ExtUIOp, mlir::arith::FPToSIOp, mlir::arith::FPToUIOp, mlir::arith::FloorDivSIOp, mlir::arith::IndexCastOp, mlir::arith::IndexCastUIOp, mlir::arith::MaxFOp, mlir::arith::MaxSIOp, mlir::arith::MaxUIOp, mlir::arith::MinFOp, mlir::arith::MinSIOp, mlir::arith::MinUIOp, mlir::arith::MulFOp, mlir::arith::MulIOp, mlir::arith::MulSIExtendedOp, mlir::arith::MulUIExtendedOp, mlir::arith::NegFOp, mlir::arith::OrIOp, mlir::arith::RemFOp, mlir::arith::RemSIOp, mlir::arith::RemUIOp, mlir::arith::SIToFPOp, mlir::arith::ShLIOp, mlir::arith::ShRSIOp, mlir::arith::ShRUIOp, mlir::arith::SubFOp, mlir::arith::SubIOp, mlir::arith::TruncFOp, mlir::arith::TruncIOp, mlir::arith::UIToFPOp, mlir::arith::XOrIOp, mlir::arith::SelectOp>() (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libFortranLower.17rc.dylib+0x5455f4)
 #9 0x000000010fe0e703 mlir::arith::ArithDialect::initialize() (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libFortranLower.17rc.dylib+0x543703)
#10 0x000000010a8ad388 std::__1::unique_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> llvm::function_ref<std::__1::unique_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> ()>::callback_fn<mlir::arith::ArithDialect* mlir::MLIRContext::getOrLoadDialect<mlir::arith::ArithDialect>()::'lambda'()>(long) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontend.17rc.dylib+0x21388)
#11 0x00000001206dbd36 mlir::MLIRContext::getOrLoadDialect(llvm::StringRef, mlir::TypeID, llvm::function_ref<std::__1::unique_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> ()>) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libFIRSupport.17rc.dylib+0x7f4d36)
#12 0x000000010a9dcd97 mlir::affine::AffineDialect::AffineDialect(mlir::MLIRContext*) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontend.17rc.dylib+0x150d97)
#13 0x000000010a8ac7a8 std::__1::unique_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> llvm::function_ref<std::__1::unique_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> ()>::callback_fn<mlir::affine::AffineDialect* mlir::MLIRContext::getOrLoadDialect<mlir::affine::AffineDialect>()::'lambda'()>(long) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontend.17rc.dylib+0x207a8)
#14 0x00000001206dbd36 mlir::MLIRContext::getOrLoadDialect(llvm::StringRef, mlir::TypeID, llvm::function_ref<std::__1::unique_ptr<mlir::Dialect, std::__1::default_delete<mlir::Dialect>> ()>) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libFIRSupport.17rc.dylib+0x7f4d36)
#15 0x000000010a8a58c3 fir::support::loadNonCodegenDialects(mlir::MLIRContext&) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontend.17rc.dylib+0x198c3)
#16 0x000000010a8a4728 Fortran::frontend::CodeGenAction::beginSourceFileAction() (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontend.17rc.dylib+0x18728)
#17 0x000000010a8a289a Fortran::frontend::FrontendAction::beginSourceFile(Fortran::frontend::CompilerInstance&, Fortran::frontend::FrontendInputFile const&) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontend.17rc.dylib+0x1689a)
#18 0x000000010a892adf Fortran::frontend::CompilerInstance::executeAction(Fortran::frontend::FrontendAction&) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontend.17rc.dylib+0x6adf)
#19 0x000000010a62b8a6 Fortran::frontend::executeCompilerInvocation(Fortran::frontend::CompilerInstance*) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libflangFrontendTool.17rc.dylib+0x38a6)
#20 0x000000010a61e460 fc1_main(llvm::ArrayRef<char const*>, char const*) (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/flang-new+0x100004460)
#21 0x000000010a61cd68 main (/Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/flang-new+0x100002d68)
Thread model: posix
InstalledDir: /Users/runner/miniforge3/conda-bld/flang-split_1695019432397/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin
flang-new: note: diagnostic msg: 
********************
```

**Comment by h-vetinari** [comment]
> just wanted to check if you'd have something against publishing osx-builds for now?

Gentle ping @isuruf

**Review by isuruf — APPROVED** [review]

**Comment by h-vetinari** [comment]
Thanks! 🙏

**Pull request merged**
